import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#564500",
        "on-primary-container": "#fefcff",
        "outline": "#717786",
        "on-secondary-fixed-variant": "#2f486a",
        "surface-container-highest": "#dde3eb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed-dim": "#afc8f0",
        "on-secondary-fixed": "#001c3a",
        "secondary-fixed": "#d4e3ff",
        "inverse-on-surface": "#ebf1f9",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0070ea",
        "on-background": "#161c22",
        "secondary-container": "#bdd6ff",
        "surface-container-high": "#e3e9f1",
        "tertiary-fixed-dim": "#edc200",
        "on-primary-fixed": "#001a41",
        "surface-container-low": "#eef4fc",
        "surface-variant": "#dde3eb",
        "secondary": "#476083",
        "inverse-surface": "#2b3137",
        "tertiary": "#725c00",
        "on-surface": "#161c22",
        "on-secondary-container": "#445d80",
        "outline-variant": "#c1c6d7",
        "on-surface-variant": "#414754",
        "surface": "#f6f9ff",
        "tertiary-container": "#cda800",
        "surface-dim": "#d4dbe2",
        "inverse-primary": "#adc7ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffe07f",
        "surface-tint": "#005bc0",
        "primary-fixed": "#d8e2ff",
        "on-error": "#ffffff",
        "surface-bright": "#f6f9ff",
        "primary": "#0059bb",
        "on-tertiary-fixed": "#231b00",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#adc7ff",
        "background": "#f6f9ff",
        "on-tertiary-container": "#4e3e00",
        "on-primary": "#ffffff",
        "surface-container": "#e8eef6",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
